version: '3.8'

services:
  mongo:
    image: mongo:5.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coworking
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5003/api/v1
    depends_on:
      - backend

volumes:
  mongo_data:
